jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sm-branch:
          - master
          - 1.12-dev
    uses: Dolly/ci-workflows/.github/workflows/shared_build_release_am_extension.yml@main
    with:
      sdks: "css"
      sm-branch: ${{ matrix.sm-branch }}
